image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: your_dockerhub_username/mse_ddm501

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
    - echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
    - docker push $IMAGE_NAME